### ISSUE TITLE
Regexp: Interpretation of backspace string escape vs word boundary anchor

### ISSUE THREAD

**Issue by ammar** [runpaint/read-ruby#104]
I hope I did not miss this in the book somewhere. A \b is interpreted as a backspace only when it occurs inside a character class, otherwise it is interpreted as a word boundary anchor.

<pre>
>> "a\b c" =~ /a[\b] c/
=> 0
>> "a\b c" =~ /a\b c/
=> nil
</pre>

I created an issue about this a couple of weeks ago, but I wasn't sure I understood the issue well or presented good examples, so I closed it. I hope this example, as well as my understanding, are a little better.

Thanks.

**Comment by runpaint** [comment]
Regexps: Anchors are not supported within character classes. Closed by b7b9c42a67c86e14cbb29b4322f2326b7b283228.
