### ISSUE TITLE
Regexp: Description of Back-reference to group named or numbered unclear

### ISSUE THREAD

**Issue by ammar** [runpaint/read-ruby#105]
It is not clear to me what the following description in the Regexp Escapes table refers to:

Back-reference to group named or numbered name (src/regexps.xml#L370)

Is it supposed to have a \k in the first column? I couldn't find a issue for it and can't tell if it is missing or pending.

Thanks.

**Comment by runpaint** [comment]
Regexps: Re-flow source; fix \k<> omission. Closed by 2e9b885dc8a6bc58b8dd6163af4db2ae3f6a4d55.
