### ISSUE TITLE
Regexp: Unicode 6.0 adds new scripts Batak, Brahmi, now included in ruby 1.9.3

### ISSUE THREAD

**Issue by ammar** [runpaint/read-ruby#108]
Please addi new scripts Batak (code: batk) and Brahmi (code: brah) to scripts list at regexp#script. They are now included in ruby 1.9.3. Mandaic (code: mand) has a separate issue.

<pre>
>> RUBY_DESCRIPTION
=> "ruby 1.9.3dev (2010-11-12 trunk 29770) [x86_64-linux]"
>> /\p{Batak}/
=> /\p{Batak}/
>> /\p{batk}/
=> /\p{batk}/
>> /\p{Brahmi}/
=> /\p{Brahmi}/
>> /\p{brah}/
=> /\p{brah}/
</pre>

Regards and thanks.

**Comment by runpaint** [comment]
I'm tracking the Unicode 6 updates in #76, so if you don't mind I'll close this.

**Comment by ammar** [comment]
I missed that issue. Please excuse the redundancy.
