### ISSUE TITLE
Regexp: \G is omitted from anchors table/coverage

### ISSUE THREAD

**Issue by ammar** [runpaint/read-ruby#120]
The start of match position anchor \G appears to be supported in ruby 1.9, but is not covered.

<pre>
>> RUBY_DESCRIPTION
=> "ruby 1.9.2p0 (2010-08-18 revision 29036) [i386-darwin9.8.0]"
>> "foo bar".scan(/\w/)
=> ["f", "o", "o", "b", "a", "r"]
>> "foo bar".scan(/\G\w/)
=> ["f", "o", "o"]
</pre>

Actually, it appears to be in ruby 1.8 as well.

Cheers and Thanks!

P.S. I wish I could contribute by submitting pull requests, instead of just throwing issues at the project. xslt is somewhat foreign to me.

**Comment by ammar** [comment]
I just noticed \G listed under Escapes, but I think it should be listed under Anchors as well. Arguable, your call of course.

Thanks

**Comment by runpaint** [comment]
Regexps: Document \G. Closed by 2b91fd19b74340a23b8872c2ad400085da74cf21.

**Comment by runpaint** [comment]
> I wish I could contribute by submitting pull requests, instead of just throwing issues
> at the project. xslt is somewhat foreign to me.

The reports are much appreciated. :-) XSLT is indeed torturous, but the chapters themselves are written in Docbook 5, which is basically HTML with more verbose element names.
