### ISSUE TITLE
spaces are not correctly rendered in Firefox on Ubuntu Linux

### ISSUE THREAD

**Issue by petervandenabeele** [runpaint/read-ruby#122]
When displaying pages, e.g.

 http://ruby.runpaint.org/methods

in Firefox (version 3.6.13) on Ubuntu Linux 10.04
frequently the spaces between words are not shown.

An example is between the words 'are' and 'known'
in the sentence:

  "Singleton methods defined on Class objects areknown as class methods."

This occurs occasionally in the text.

**Comment by petervandenabeele** [comment]
This is in Chapter VII. Methods, part B. Singleton Methods

**Comment by runpaint** [comment]
I'm aware of the problem, and unfortunately it affects multiple chapters on all browsers. I'm repairing as I go. I believe _Methods_ should be fixed with commits  f8f1f42e1d7dfc92c43edc2b170d2bd440cdcb57 and 8561cab00a6f0c9687b6d6b9f0dd271467640dae.
