### ISSUE TITLE
DATA's class

### ISSUE THREAD

**Issue by michaeledgar** [runpaint/read-ruby#125]
In the section on **END** ([1.B.3](http://goo.gl/hb8W)), you note that `DATA` is an `IO`. It is more specifically (when initialized) an instance of `File`, in both 1.8.7 and 1.9.2 on my machine.
### temp.rb

```
puts "> #{DATA.class}"
__END__
hello world
```
### In bash:

```
ruby temp.rb
> File
```

**Comment by runpaint** [comment]
Programs: Fix class of DATA. Closed by 87283cf8b38e439b9abdaf7efcf61e53760534c0.
