### ISSUE TITLE
newline should not be whitespace

### ISSUE THREAD

**Issue by coatl** [runpaint/read-ruby#20]
In http://ruby.runpaint.org/programs#lexical under 'Whitespace', you state:
  Whitespace consists only of U＋0009–U＋000D and the space character (U＋0020)
This range includes the ascii newline character, U+000A. Newline is not really whitespace, at least not always. Newlines preceded by \ or a binary operator (and some other things...) are whitespace, but otherwise newlines behave lexically much like semicolons.

Newlines are complicated enough to deserve a section of their own. I guess you did expand somewhat on this issue under 'Statement Terminators', but the list in that section is incomplete. For instance, newlines following ( { [ are not statement terminators.

**Comment by runpaint** [comment]
Does 8100488b55edd0b974419b16de181cce3a6872bd address the issue? (http://ruby.runpaint.org/programs#whitespace). The dual role of \n is mentioned in Whitespace, and the Statement Terminators and Newlines section is expanded to mention the case of `(`, `{`, and `[`.

**Comment by coatl** [comment]
8100488 is better, but still has some issues.

In 'Whitespace', you changed 'U＋0009–U＋000D' to 'U＋0009, U＋000A–U＋000D', which is equivalent to what you had before. I think maybe you meant 'U＋0009, U＋000B–U＋000D'?

Regarding 'Statement Terminators & Newlines', there are actually a whole bunch of other cases. I said 'for instance' above, because I didn't want to go and look up the whole list... but here's as many as I can find:

Newlines are treated as whitespace when following these keywords:

   or not and if unless then elsif else class module def
   while until begin for in case when ensure defined? alias undef

Also: 
  following rescue when used as an operator.
  if the next non-ws token following nl is : 

I think there are maybe even a couple more cases....

Some of these are arguable; should newline be whitespace after these keywords:
   do then else begin ensure  
It doesn't really matter, since the semantics end up the same either way.

I gleaned this info from the source code of my project RubyLexer, which ought to be extremely accurate at this point.

I don't know how far you want to take this project. Are you trying to make a pedantically correct reference work? Or a descriptive text suitable for beginning & intermediate readers? If the latter, what you have now is probably sufficient.

**Comment by runpaint** [comment]
Thanks. :-) I've fixed the range in ae3547033667aff5554f05b689f9978b9a1b377f and added the list of keywords. I've been wrestling on the issue of project scope myself--http://ruby.runpaint.org/punctuation , for example, was originally part of Programs, but I relegated it to an appendix because it seemed too overbearing--but hopefully the current commit provides a reasonable compromise for now.
