### ISSUE TITLE
Appendix Punctuation: colon description is a little muddy

### ISSUE THREAD

**Issue by coatl** [runpaint/read-ruby#22]
The description of colon is a little unclear, and even a little inaccurate. I recommend replacing it with this text:

A colon (U＋003A) 

At the beginning of an expression
    Creates a symbol from the following identifier or string. (Unless followed by another colon.)
In operator context
    Separates the then clause from the else clause in a ternary expression. 
In operator context inside a hash literal
    Separates symbol keys from their corresponding values. 
When followed by another colon
    Double colons serves as the scope operator. It separating the names of nested constants when followed by a capitalized word (it can also appear on its own at the beginning of an expression). When followed by an uncapitalized word or operator, it separates the receiver from the method name in a method call (like dot).

**Comment by runpaint** [comment]
Punctuation: Clarify ':' (h/t coatl; closed by 33ae6698a683bfecf7a448e5b0ae23e07ebc4277)
