### ISSUE TITLE
Appendix Punctuation: missed a couple cases for comma

### ISSUE THREAD

**Issue by coatl** [runpaint/read-ruby#23]

**Comment by coatl** [comment]
ack, hit the button too early. here's what should be in the description:

comma can also be used in hash literals and the list of method names passed to undef. 

I would also expand 'assignment expressions' to 'assignment lvalues and rvalues'.

**Comment by runpaint** [comment]
Punctuation: Clarify ',' (h/t coatl; closed by ca36b362f835f654c0d875baf80ec548e71dc5a8)
