### ISSUE TITLE
Appendix Punctuation: newlines

### ISSUE THREAD

**Issue by coatl** [runpaint/read-ruby#26]
several errors in the newlines section of the appendix. 

Form feed and carriage return by themselves are NOT considered newlines.

Newline is not required inside if and def, et cetera. You may use semicolon instead. (The section on semicolons should be changed to reflect this too.)

**Comment by runpaint** [comment]
Punctuation: Clarify \n (h/t coatl; closed by 5171b8c21cbf4665aba4deed54e162e049f0a86e)
