### ISSUE TITLE
Appendix Punctuation: vertical line

### ISSUE THREAD

**Issue by coatl** [runpaint/read-ruby#32]
I recommend replacing the vertical line section in the appendix with:

A vertical line (U＋007C) is an bitwise or operator when used singly, boolean or when followed by another, and serves to delimit the parameter list of a block.

**Comment by runpaint** [comment]
Punctuation: Clarify '|'. (h/t coatl; closed by 8acb042439704f4a5e7b2d298139a88878d833a6)

**Comment by coatl** [comment]
Just one final little nit here: you still are missing the closing paren after U＋007C in this section.

**Comment by runpaint** [comment]
Fixed in 889f5a716e3e20e63f040326c7b6ea436eb02177
