### ISSUE TITLE
Fix fonts on Win7

### ISSUE THREAD

**Issue by runpaint** [runpaint/read-ruby#38]
Apparently, the fonts are overly large on Gecko/Webkit under Windows 7. This may require a virtual machine set up because I don't have a Windows box.

**Comment by larsch** [comment]
The font renders poorly under both Chrome and Firefox under Windows XP also. It looks like the font is poorly hinted (some letters are 1 pixel taller than others). Could also be a weakness in the font engine, but it looks horrible still. http://tinypic.com/r/2rfbssy/7

**Comment by runpaint** [comment]
I've changed the body font. Does that look better?

**Comment by larsch** [comment]
Yes, much better. http://tinypic.com/r/21etf5z/7

**Comment by runpaint** [comment]
The original reporter of the Windows 7 problem also confirms that this fix is good, so I'm closing the ticket.
