### ISSUE TITLE
Printable pdf

### ISSUE THREAD

**Issue by grosser** [runpaint/read-ruby#41]
Would e nice to have a printable version, since i could not get the `rake html` to work i rolled my own http://grosser.it/2010/09/21/read-ruby-the-ruby-1-9-book-as-pdf but its far from 'perfect'

**Comment by runpaint** [comment]
There will certainly be a PDF. That's part of the reason I'm in the process of converting everything to Docbook.

**Comment by runpaint** [comment]
Here's a start: http://ruby.runpaint.org/read-ruby.pdf . There are still various things I want to fix before linking it from anywhere. Feel free to open tickets about any problems you find.

**Comment by grosser** [comment]
looks good to me, its already better then my html-grab + pdfkit version :)
