### ISSUE TITLE
Error in one of examples at http://ruby.runpaint.org/variables#defined

### ISSUE THREAD

**Issue by barnaba** [runpaint/read-ruby#42]
One of examples says:

```
var = defined? true and nil #=> "true"
```

but I checked with irb and this evaluates to nil:
    irb(main):004:0> var = defined? true and nil
    => nil

**Comment by runpaint** [comment]
Variables: Fix example; closed by 7399338ab0816ef7fc8f91debde7138e07d3e6bb
