### ISSUE TITLE
Programs/Statement Terminators & Newlines: words fused at EOL

### ISSUE THREAD

**Issue by ammar** [runpaint/read-ruby#71]
In src/programs.xml:474

First paragraph, http://ruby.runpaint.org/programs#statement-terminators

<pre>
  statementterminator => statement terminator
  ornewline => or newline
  naturalseparation => natural separation
  notterminate => not terminate
</pre>

Thanks.

**Comment by runpaint** [comment]
Programs: Fix linebreaks by re-wrapping. Closed by 9ac96e1a6f5eadb755cff6c06a0094eeeccc157e. h/t ammar
