### ISSUE TITLE
Regexp: Missing coverage of possessive quantifiers?

### ISSUE THREAD

**Issue by ammar** [runpaint/read-ruby#74]
Possessive quantifiers appear to be supported in 1.9:

<pre>
   >> re = /cats?+/
   => /cats?+/
   >> re.match "cat"
   => #MatchData "cat"
   >> re.match "cats"
   => #MatchData "cats"
   >> re.match "catsssss"
   => #MatchData "cats"
   >> re.match "cats+"
   => #MatchData "cats"
</pre>

Thanks.

**Comment by runpaint** [comment]
Regexps: Explain possessive quantifiers. Closed by 15638c28f903b7537d40718c93b56424e24f034d; ht/t ammar
